// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateItemData, CreateItemResponses, CreateListData, CreateListResponses, DeleteItemData, DeleteItemResponses, DeleteListData, DeleteListResponses, GetApiAuthUserData, GetApiAuthUserResponses, GetItemsData, GetItemsResponses, GetListData, GetListErrors, GetListResponses, GetListsData, GetListsResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthLogoutData, PostApiAuthLogoutResponses, PostApiAuthRegisterData, PostApiAuthRegisterResponses, SetItemCompletionData, SetItemCompletionResponses, UpdateItemData, UpdateItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>): RequestResult<PostApiAuthLoginResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthRegisterData, ThrowOnError>): RequestResult<PostApiAuthRegisterResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiAuthRegisterResponses, unknown, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLogoutData, ThrowOnError>): RequestResult<PostApiAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostApiAuthLogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

export const getApiAuthUser = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthUserData, ThrowOnError>): RequestResult<GetApiAuthUserResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetApiAuthUserResponses, unknown, ThrowOnError>({ url: '/api/auth/user', ...options });

export const getLists = <ThrowOnError extends boolean = false>(options?: Options<GetListsData, ThrowOnError>): RequestResult<GetListsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetListsResponses, unknown, ThrowOnError>({ url: '/api/todo-lists', ...options });

export const createList = <ThrowOnError extends boolean = false>(options: Options<CreateListData, ThrowOnError>): RequestResult<CreateListResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateListResponses, unknown, ThrowOnError>({
    url: '/api/todo-lists',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteList = <ThrowOnError extends boolean = false>(options: Options<DeleteListData, ThrowOnError>): RequestResult<DeleteListResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteListResponses, unknown, ThrowOnError>({ url: '/api/todo-lists/{listId}', ...options });

export const getList = <ThrowOnError extends boolean = false>(options: Options<GetListData, ThrowOnError>): RequestResult<GetListResponses, GetListErrors, ThrowOnError> => (options.client ?? client).get<GetListResponses, GetListErrors, ThrowOnError>({ url: '/api/todo-lists/{listId}', ...options });

export const getItems = <ThrowOnError extends boolean = false>(options: Options<GetItemsData, ThrowOnError>): RequestResult<GetItemsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetItemsResponses, unknown, ThrowOnError>({ url: '/api/todo-lists/{listId}/items', ...options });

export const createItem = <ThrowOnError extends boolean = false>(options: Options<CreateItemData, ThrowOnError>): RequestResult<CreateItemResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateItemResponses, unknown, ThrowOnError>({
    url: '/api/todo-lists/{listId}/items',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteItem = <ThrowOnError extends boolean = false>(options: Options<DeleteItemData, ThrowOnError>): RequestResult<DeleteItemResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteItemResponses, unknown, ThrowOnError>({ url: '/api/todo-lists/{listId}/items/{itemId}', ...options });

export const updateItem = <ThrowOnError extends boolean = false>(options: Options<UpdateItemData, ThrowOnError>): RequestResult<UpdateItemResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateItemResponses, unknown, ThrowOnError>({
    url: '/api/todo-lists/{listId}/items/{itemId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const setItemCompletion = <ThrowOnError extends boolean = false>(options: Options<SetItemCompletionData, ThrowOnError>): RequestResult<SetItemCompletionResponses, unknown, ThrowOnError> => (options.client ?? client).put<SetItemCompletionResponses, unknown, ThrowOnError>({
    url: '/api/todo-lists/{listId}/items/{itemId}/completion',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
