// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateTodoItemRequest = {
    title?: string | null;
};

export type CreateTodoListRequest = {
    name?: string | null;
};

export type LoginRequest = {
    email?: string | null;
    password?: string | null;
    rememberMe?: boolean | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type RegisterRequest = {
    email?: string | null;
    password?: string | null;
    confirmPassword?: string | null;
};

export type SetTodoItemCompletionRequest = {
    isCompleted?: boolean;
};

export type TodoItemDto = {
    id?: string;
    title?: string | null;
    isCompleted?: boolean;
    lastModified?: string | null;
};

export type TodoListDto = {
    id?: string;
    name?: string | null;
    lastModified?: string;
    itemCount?: number;
    completedItemCount?: number;
};

export type TodoListFullDto = {
    id?: string;
    name?: string | null;
    lastModified?: string;
    items?: Array<TodoItemDto> | null;
};

export type UpdateTodoItemRequest = {
    title?: string | null;
};

export type UserInfo = {
    userId?: string | null;
    userName?: string | null;
    email?: string | null;
    isAuthenticated?: boolean;
};

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type GetApiAuthUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/user';
};

export type GetApiAuthUserResponses = {
    /**
     * OK
     */
    200: UserInfo;
};

export type GetApiAuthUserResponse = GetApiAuthUserResponses[keyof GetApiAuthUserResponses];

export type GetListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todo-lists';
};

export type GetListsResponses = {
    /**
     * OK
     */
    200: Array<TodoListDto>;
};

export type GetListsResponse = GetListsResponses[keyof GetListsResponses];

export type CreateListData = {
    body: CreateTodoListRequest;
    path?: never;
    query?: never;
    url: '/api/todo-lists';
};

export type CreateListResponses = {
    /**
     * Created
     */
    201: TodoListDto;
};

export type CreateListResponse = CreateListResponses[keyof CreateListResponses];

export type DeleteListData = {
    body?: never;
    path: {
        listId: string;
    };
    query?: never;
    url: '/api/todo-lists/{listId}';
};

export type DeleteListResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteListResponse = DeleteListResponses[keyof DeleteListResponses];

export type GetListData = {
    body?: never;
    path: {
        listId: string;
    };
    query?: never;
    url: '/api/todo-lists/{listId}';
};

export type GetListErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetListResponses = {
    /**
     * OK
     */
    200: TodoListFullDto;
};

export type GetListResponse = GetListResponses[keyof GetListResponses];

export type CreateItemData = {
    body: CreateTodoItemRequest;
    path: {
        listId: string;
    };
    query?: never;
    url: '/api/todo-lists/{listId}/items';
};

export type CreateItemResponses = {
    /**
     * OK
     */
    200: TodoItemDto;
};

export type CreateItemResponse = CreateItemResponses[keyof CreateItemResponses];

export type DeleteItemData = {
    body?: never;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/todo-lists/items/{itemId}';
};

export type DeleteItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteItemResponse = DeleteItemResponses[keyof DeleteItemResponses];

export type UpdateItemData = {
    body: UpdateTodoItemRequest;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/todo-lists/items/{itemId}';
};

export type UpdateItemResponses = {
    /**
     * OK
     */
    200: TodoItemDto;
};

export type UpdateItemResponse = UpdateItemResponses[keyof UpdateItemResponses];

export type SetItemCompletionData = {
    body: SetTodoItemCompletionRequest;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/todo-lists/items/{itemId}/completion';
};

export type SetItemCompletionResponses = {
    /**
     * OK
     */
    200: TodoItemDto;
};

export type SetItemCompletionResponse = SetItemCompletionResponses[keyof SetItemCompletionResponses];
