<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
    <PackageReference Include="Aspire.Hosting.Azure.Sql" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" />
    <!--<PackageReference Include="CommunityToolkit.Aspire.Microsoft.Data.Sqlite" />-->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzraTasks.Core\AzraTasks.Core.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\AzraTasks.Data\AzraTasks.Data.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\AzraTasks\AzraTasks.csproj" />
  </ItemGroup>

</Project>
