# =============================================================================
# Service Principal References
# =============================================================================
# Auto-generated by Setup.ps1 - These reference the Azure AD App Registrations
# created during project setup. They are added as members of the admins group
# to allow CI/CD pipelines to manage infrastructure resources.
#
# App Registration:   AzraTasks-GitHubActions
# Infra Registration: AzraTasks-GitHubActionsInfra
# =============================================================================

data "azuread_service_principal" "app_sp" {
  display_name = "AzraTasks-GitHubActions"
}

data "azuread_service_principal" "infra_sp" {
  display_name = "AzraTasks-GitHubActionsInfra"
}

resource "azuread_group_member" "app_sp" {
  group_object_id  = azuread_group.admins_group.object_id
  member_object_id = data.azuread_service_principal.app_sp.object_id
}

resource "azuread_group_member" "infra_sp" {
  group_object_id  = azuread_group.admins_group.object_id
  member_object_id = data.azuread_service_principal.infra_sp.object_id
}
